custom_sql:
- comparisons:
  - operator: LT
    threshold_value: 0.0
    type: threshold
  description: check user count
  name: Custom SQL rule
  schedule:
    interval_minutes: 120
    start_time: '2023-06-05T13:00:00+00:00'
    type: fixed
  sql: |
    select distinct email from merakidw.fact.cisco_users where deleted_at is null
